config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  resources :projects
  resources :users, only: [:index, :new, :creata, :edit, :update, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :project
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:user, :admin, :manager]
  
  after_initialize :default_role, :if => :new_record?

  def default_role
    self.role ||= :user
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
        projects_path
    end
    
    protected
    def authenticate_user!
        if user_signed_in?
            super
        else
            redirect_to new_user_session_path, :alert => 'You are not authorized!'
        end
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) do |user_params|
            user_params.permit({ roles: [] }, :email, :password, :password_confirmation)
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def post
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = Project.all                                                                                     
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params
    @project.user_id = current_user.id
    if @project.save
      redirect_to projects_path, notice: 'Project in successfully create'
    else
      flash.now[:alert] = 'Invalid create Project'
      render :new
    end
  end

  def edit 
    @project = Project.find_by id: params[:id]
  end

  def update
    @project = Project.find_by id: params[:id]
    if @project.update project_params
      redirect_to projects_path, notice: 'Project in successfully update' 
    else
      flash.now[:alert] = 'Invalid update Project'
      render :edit
    end
  end

  def show
    @project = Project.find_by id: params[:id]
  end

  def destroy
    @project = Project.find_by id: params[:id]
    if @project.delete
      redirect_to projects_path, notice: 'Project in successfully destroy'
    else
      flash.now[:alert] = 'Invalid delete Project'
      render :index
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :body)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new user_params
        if @user.save
            redirect_to users_path, notice: 'User in successfully create'
        else
            flash.now[:alert] = 'Invalid create User'
            render :new
        end
    end

    def edit 
        @user = User.find_by id: params[:id]
    end

    def update
        @user = User.find_by id: params[:id]
        puts @user
        if @user.update user_params
            redirect_to users_path, notice: 'User in successfully update' 
        else
            flash.now[:alert] = 'Invalid update User'
            render :edit
        end
    end


    def destroy
        @user = User.find_by id: params[:id]
        puts @user
        if @user.delete
            flash.now[:notice] = 'User in successfully destroy'
            redirect_to users_path
        else
            flash.now[:alert] = 'Invalid delete User'
            render :index
        end
    end

    private

    def user_params
        params.require(:user).permit(:role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasecampRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <% if notice.present? %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

app/views/navbar/_navbar.html.erb
    <nav class="navbar navbar-expand-lg bg-light mb-5">
        <div class="container">
          <a class="navbar-brand" href="/">Main</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to 'Projects',  projects_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Users',  users_path, class: "nav-link" %>
              </li>
            </ul>
            <div class="d-flex">
                <%= current_user.role %> || <%= current_user.email %>
            </div>
          </div>
        </div>
    </nav>

app/views/pages/home.html.erb
<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem; background-color: #508bfc;">
          <div class="card-body p-5 text-center d-flex m-auto">
            <% if current_user %>
                <%= link_to 'Dashboard', projects_path, class: "btn btn-lg btn-block btn-warning m-2" %>
                <%=  button_to 'Log out', destroy_user_session_path, method: :delete, class: "btn btn-lg btn-block btn-danger m-2" %>
            <% else %>
                <%= link_to 'Login', new_user_session_path, class: "btn btn-lg btn-block btn-success m-2" %>
                <%= link_to 'Register', new_user_registration_path, class: "btn btn-lg btn-block btn-secondary m-2" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/projects/edit.html.erb
<%= render 'navbar/navbar' %>
<h1>Edit project</h1>

<%= link_to 'Back', projects_path, :class => "card-link btn btn-secondary mt-3 mb-3" %>
<% if @project.user_id ===  current_user.id %>
  <%= form_for @project, :html => {:class => "form-horizontal"} do |f| %>
        <div class="form-group">
          <%= f.label :title, "Title:", class: "col-md-4 control-label" %>
          <div class="col-md-6">
            <%= f.text_field :title, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :body, "Descptions:", class: "col-md-4 control-label" %>
          <div class="col-md-6">
            <%= f.text_field :body, class: "form-control" %>
          </div>
        </div>

        <%= f.submit "Submit", class: "btn btn-default btn-primary mt-3" %>
  <% end %>
<% end %>

app/views/projects/index.html.erb
<%= render 'navbar/navbar' %>
<h1>Projects</h1>

<%= link_to 'Create project', new_project_path, :class => "card-link btn btn-success mt-3 mb-3" %>

<div class="row">
    <% @projects.each do |project| %>
        <div class="col-3">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title"><%= project.title %></h5>
                    <p class="card-text"><%= project.body %></p>
                    <% if project.user_id ===  current_user.id %>
                        <div class="d-flex">
                            <%= link_to project_path(project), class: "card-link btn btn-success m-1" do %>
                                <i class="bi bi-eye-fill"></i>
                            <% end %>
                            <%= link_to edit_project_path(project), class: "card-link btn btn-primary m-1" do %>
                                <i class="bi bi-pencil-square"></i>
                            <% end %>
                            <%= button_to project_path(project), method: 'delete', data: { confirm: 'Are you sure?' }, class: "card-link btn btn-danger m-1" do %>
                                <i class="bi bi-trash3-fill"></i>
                            <% end %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/projects/new.html.erb
<%= render 'navbar/navbar' %>
<h1>New project</h1>

<%= link_to 'Back', projects_path, :class => "card-link btn btn-secondary mt-3 mb-3" %>

<%= form_for @project, :html => {:class => "form-horizontal"} do |f| %>
      <div class="form-group">
        <%= f.label :title, "Title:", class: "col-md-4 control-label" %>
        <div class="col-md-6">
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :body, "Descptions:", class: "col-md-4 control-label" %>
        <div class="col-md-6">
          <%= f.text_field :body, class: "form-control" %>
        </div>
      </div>

      <%= f.submit "Submit", class: "btn btn-default btn-primary mt-3" %>
 <% end %>

app/views/projects/show.html.erb
<%= render 'navbar/navbar' %>
<h1>Project show</h1>

<%= link_to 'Back', projects_path, :class => "card-link btn btn-secondary mt-3 mb-3" %>

<div class="card">
    <div class="card-header">
        <%= @project.title %>
    </div>
    <div class="card-body">
        <blockquote class="blockquote mb-0">
            <footer class="blockquote-footer"><%= @project.body %></footer>
        </blockquote>
    </div>
</div>

app/views/users/edit.html.erb
<%= render 'navbar/navbar' %>
<h1>Edit user role</h1>

<%= link_to 'Back', users_path, :class => "card-link btn btn-secondary mt-3 mb-3" %>

<%= form_for @user, :html => {:class => "form-horizontal"} do |f| %>
      <div class="form-group">
        <%= f.label :email, "Email:", class: "col-md-4 control-label" %>
        <div class="col-md-6">
          <%= f.text_field :email, class: "form-control-plaintext", :readonly => true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :role, "User Role:", class: "col-md-4 control-label mb-3" %>
        <div class="col-md-6">
          <%= f.select :role, options_for_select(User.roles.keys.to_a, params[:role]), {}, class: 'form-select' %>
        </div>
      </div>

      <%= f.submit "Submit", class: "btn btn-default btn-primary mt-3" %>
 <% end %>

app/views/users/index.html.erb
<%= render 'navbar/navbar' %>

<h1>Users</h1>
<% if current_user.admin? %>
  <%= link_to 'Create user', new_user_path, :class => "card-link btn btn-success mt-3 mb-3" %>
<% end %>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
      <th scope="col">Role</th>
      <% if current_user.admin? %>
      <th scope="col">Action</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  
    <% @users.each do |user| %>
        <tr>
        <th scope="row"><%= user.id %></th>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <% if current_user.admin? %>
          <td class="d-flex">
              <%= link_to edit_user_path(user), class: "card-link btn btn-primary m-1" do %>
                <i class="bi bi-pencil-square"></i>
              <% end %>
              <%= button_to user_path(user), method: 'delete', data: { confirm: 'Are you sure?' }, class: "card-link btn btn-danger m-1" do %>
                <i class="bi bi-trash3-fill"></i>
              <% end %>
          </td>
        <% end %>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<%= render 'navbar/navbar' %>
<h1>New User</h1>

<%= link_to 'Back', projects_path, :class => "card-link btn btn-secondary mt-3 mb-3" %>
<% if current_user.admin? %>
<%= form_for @user, :html => {:class => "form-horizontal"} do |f| %>
      <div class="form-group">
        <%= f.label :email, "Email:", class: "col-md-4 control-label" %>
        <div class="col-md-6">
          <%= f.text_field :email, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password, "Password:", class: "col-md-4 control-label" %>
        <div class="col-md-6">
          <%= f.text_field :password, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :role, "User Role:", class: "col-md-4 control-label mb-3" %>
        <div class="col-md-6">
          <%= f.select :role, options_for_select(User.roles.keys.to_a, params[:role]), {}, class: 'form-select' %>
        </div>
      </div>

      <%= f.submit "Submit", class: "btn btn-default btn-primary mt-3" %>
 <% end %>
 <% end %>